# Generated by Django 5.2.1 on 2025-05-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('restaurant_owner', 'Resaurant Owner'), ('franchise_owner', 'Franchise Owner')], max_length=128),
        ),
    ]
