# Generated by Django 5.2.1 on 2025-06-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_menucategory_order_remove_franchise_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='name',
            field=models.CharField(default='franchise name', max_length=255),
            preserve_default=False,
        ),
    ]
