# Generated by Django 5.2.1 on 2025-06-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_franchise_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='name',
            field=models.CharField(default='outlet 1', max_length=255),
            preserve_default=False,
        ),
    ]
